runtime: nodejs22
instance_class: F1

handlers:
  - url: /assets/(.*)
    static_files: dist/assets/\1
    upload: dist/assets/.*

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html